mysql:
  build: mysql/.

elasticsearch:
  build: es/.
  environment: 
   - ES_MIN_SIZE=2g
   - ES_MAX_SIZE=2g
   - ES_HEAP_SIZE=2g
  ports:
   - "9200:9200"

nginx:
  build: nginx/.
  links:
   - mysql:db
   - elasticsearch:es     
  ports:
   - "8000:80"  
  command: supervisord -n

